on: 
  workflow_dispatch:    
  schedule:
    - cron: 0 0,12 * * *

jobs:
  check-usage:
    name: "Check usage"
    runs-on: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: "Run"
        run: bun install && bun test
        


  