on: 
  workflow_dispatch:    
  schedule:
    - cron: 0 0,12 * * *

jobs:
  check-usage:
    name: "Health-check"
    runs-on: ubuntu-latest
    steps:
      - name: "Run"
        run: |
          curl -fsSL https://bun.sh/install | bash 
          source /home/runner/.bashrc 
          bun install && bun test
        


  
